package com.peer.dog.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PeerVarietiesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    public PeerVarietiesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVarietiesIsNull() {
            addCriterion("varieties is null");
            return (Criteria) this;
        }

        public Criteria andVarietiesIsNotNull() {
            addCriterion("varieties is not null");
            return (Criteria) this;
        }

        public Criteria andVarietiesEqualTo(String value) {
            addCriterion("varieties =", value, "varieties");
            return (Criteria) this;
        }

        public Criteria andVarietiesNotEqualTo(String value) {
            addCriterion("varieties <>", value, "varieties");
            return (Criteria) this;
        }

        public Criteria andVarietiesGreaterThan(String value) {
            addCriterion("varieties >", value, "varieties");
            return (Criteria) this;
        }

        public Criteria andVarietiesGreaterThanOrEqualTo(String value) {
            addCriterion("varieties >=", value, "varieties");
            return (Criteria) this;
        }

        public Criteria andVarietiesLessThan(String value) {
            addCriterion("varieties <", value, "varieties");
            return (Criteria) this;
        }

        public Criteria andVarietiesLessThanOrEqualTo(String value) {
            addCriterion("varieties <=", value, "varieties");
            return (Criteria) this;
        }

        public Criteria andVarietiesLike(String value) {
            addCriterion("varieties like", value, "varieties");
            return (Criteria) this;
        }

        public Criteria andVarietiesNotLike(String value) {
            addCriterion("varieties not like", value, "varieties");
            return (Criteria) this;
        }

        public Criteria andVarietiesIn(List<String> values) {
            addCriterion("varieties in", values, "varieties");
            return (Criteria) this;
        }

        public Criteria andVarietiesNotIn(List<String> values) {
            addCriterion("varieties not in", values, "varieties");
            return (Criteria) this;
        }

        public Criteria andVarietiesBetween(String value1, String value2) {
            addCriterion("varieties between", value1, value2, "varieties");
            return (Criteria) this;
        }

        public Criteria andVarietiesNotBetween(String value1, String value2) {
            addCriterion("varieties not between", value1, value2, "varieties");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlIsNull() {
            addCriterion("peer_varieties_url is null");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlIsNotNull() {
            addCriterion("peer_varieties_url is not null");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlEqualTo(String value) {
            addCriterion("peer_varieties_url =", value, "peerVarietiesUrl");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlNotEqualTo(String value) {
            addCriterion("peer_varieties_url <>", value, "peerVarietiesUrl");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlGreaterThan(String value) {
            addCriterion("peer_varieties_url >", value, "peerVarietiesUrl");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlGreaterThanOrEqualTo(String value) {
            addCriterion("peer_varieties_url >=", value, "peerVarietiesUrl");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlLessThan(String value) {
            addCriterion("peer_varieties_url <", value, "peerVarietiesUrl");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlLessThanOrEqualTo(String value) {
            addCriterion("peer_varieties_url <=", value, "peerVarietiesUrl");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlLike(String value) {
            addCriterion("peer_varieties_url like", value, "peerVarietiesUrl");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlNotLike(String value) {
            addCriterion("peer_varieties_url not like", value, "peerVarietiesUrl");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlIn(List<String> values) {
            addCriterion("peer_varieties_url in", values, "peerVarietiesUrl");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlNotIn(List<String> values) {
            addCriterion("peer_varieties_url not in", values, "peerVarietiesUrl");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlBetween(String value1, String value2) {
            addCriterion("peer_varieties_url between", value1, value2, "peerVarietiesUrl");
            return (Criteria) this;
        }

        public Criteria andPeerVarietiesUrlNotBetween(String value1, String value2) {
            addCriterion("peer_varieties_url not between", value1, value2, "peerVarietiesUrl");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table peer_varieties
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 24 00:24:30 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table peer_varieties
     *
     * @mbggenerated Mon Sep 24 00:24:30 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}