package com.peer.dog.dao.entity;

import java.util.Date;

public class UserPeerRela {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_peer_rela.id
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_peer_rela.user_id
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_peer_rela.peer_id
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    private Integer peerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_peer_rela.rela
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    private Integer rela;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_peer_rela.create_time
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_peer_rela.last_update_time
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_peer_rela.id
     *
     * @return the value of user_peer_rela.id
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_peer_rela.id
     *
     * @param id the value for user_peer_rela.id
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_peer_rela.user_id
     *
     * @return the value of user_peer_rela.user_id
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_peer_rela.user_id
     *
     * @param userId the value for user_peer_rela.user_id
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_peer_rela.peer_id
     *
     * @return the value of user_peer_rela.peer_id
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    public Integer getPeerId() {
        return peerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_peer_rela.peer_id
     *
     * @param peerId the value for user_peer_rela.peer_id
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    public void setPeerId(Integer peerId) {
        this.peerId = peerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_peer_rela.rela
     *
     * @return the value of user_peer_rela.rela
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    public Integer getRela() {
        return rela;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_peer_rela.rela
     *
     * @param rela the value for user_peer_rela.rela
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    public void setRela(Integer rela) {
        this.rela = rela;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_peer_rela.create_time
     *
     * @return the value of user_peer_rela.create_time
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_peer_rela.create_time
     *
     * @param createTime the value for user_peer_rela.create_time
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_peer_rela.last_update_time
     *
     * @return the value of user_peer_rela.last_update_time
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_peer_rela.last_update_time
     *
     * @param lastUpdateTime the value for user_peer_rela.last_update_time
     *
     * @mbggenerated Sun Jul 15 23:58:33 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}