package com.peer.dog.dao;

import com.peer.dog.dao.entity.PeerVarieties;
import com.peer.dog.dao.entity.PeerVarietiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PeerVarietiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int countByExample(PeerVarietiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int deleteByExample(PeerVarietiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int insert(PeerVarieties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int insertSelective(PeerVarieties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    List<PeerVarieties> selectByExampleWithRowbounds(PeerVarietiesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    List<PeerVarieties> selectByExample(PeerVarietiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    PeerVarieties selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") PeerVarieties record, @Param("example") PeerVarietiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int updateByExample(@Param("record") PeerVarieties record, @Param("example") PeerVarietiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int updateByPrimaryKeySelective(PeerVarieties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_varieties
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int updateByPrimaryKey(PeerVarieties record);
}