package com.peer.dog.dao;

import com.peer.dog.dao.entity.PeerUser;
import com.peer.dog.dao.entity.PeerUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PeerUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_user
     *
     * @mbggenerated Sun Jun 24 18:26:18 CST 2018
     */
    int countByExample(PeerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_user
     *
     * @mbggenerated Sun Jun 24 18:26:18 CST 2018
     */
    int deleteByExample(PeerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_user
     *
     * @mbggenerated Sun Jun 24 18:26:18 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_user
     *
     * @mbggenerated Sun Jun 24 18:26:18 CST 2018
     */
    int insert(PeerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_user
     *
     * @mbggenerated Sun Jun 24 18:26:18 CST 2018
     */
    int insertSelective(PeerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_user
     *
     * @mbggenerated Sun Jun 24 18:26:18 CST 2018
     */
    List<PeerUser> selectByExampleWithRowbounds(PeerUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_user
     *
     * @mbggenerated Sun Jun 24 18:26:18 CST 2018
     */
    List<PeerUser> selectByExample(PeerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_user
     *
     * @mbggenerated Sun Jun 24 18:26:18 CST 2018
     */
    PeerUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_user
     *
     * @mbggenerated Sun Jun 24 18:26:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") PeerUser record, @Param("example") PeerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_user
     *
     * @mbggenerated Sun Jun 24 18:26:18 CST 2018
     */
    int updateByExample(@Param("record") PeerUser record, @Param("example") PeerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_user
     *
     * @mbggenerated Sun Jun 24 18:26:18 CST 2018
     */
    int updateByPrimaryKeySelective(PeerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_user
     *
     * @mbggenerated Sun Jun 24 18:26:18 CST 2018
     */
    int updateByPrimaryKey(PeerUser record);
}