package com.peer.dog.dao;

import com.peer.dog.dao.entity.Peer;
import com.peer.dog.dao.entity.PeerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PeerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int countByExample(PeerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int deleteByExample(PeerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int insert(Peer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int insertSelective(Peer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    List<Peer> selectByExampleWithRowbounds(PeerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    List<Peer> selectByExample(PeerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    Peer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Peer record, @Param("example") PeerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int updateByExample(@Param("record") Peer record, @Param("example") PeerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int updateByPrimaryKeySelective(Peer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbggenerated Tue Feb 12 20:26:08 CST 2019
     */
    int updateByPrimaryKey(Peer record);
}