package com.peer.dog.dao;

import com.peer.dog.dao.entity.UserPeerRela;
import com.peer.dog.dao.entity.UserPeerRelaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserPeerRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_peer_rela
     *
     * @mbggenerated Tue Apr 30 21:29:10 CST 2019
     */
    int countByExample(UserPeerRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_peer_rela
     *
     * @mbggenerated Tue Apr 30 21:29:10 CST 2019
     */
    int deleteByExample(UserPeerRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_peer_rela
     *
     * @mbggenerated Tue Apr 30 21:29:10 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_peer_rela
     *
     * @mbggenerated Tue Apr 30 21:29:10 CST 2019
     */
    int insert(UserPeerRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_peer_rela
     *
     * @mbggenerated Tue Apr 30 21:29:10 CST 2019
     */
    int insertSelective(UserPeerRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_peer_rela
     *
     * @mbggenerated Tue Apr 30 21:29:10 CST 2019
     */
    List<UserPeerRela> selectByExampleWithRowbounds(UserPeerRelaExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_peer_rela
     *
     * @mbggenerated Tue Apr 30 21:29:10 CST 2019
     */
    List<UserPeerRela> selectByExample(UserPeerRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_peer_rela
     *
     * @mbggenerated Tue Apr 30 21:29:10 CST 2019
     */
    UserPeerRela selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_peer_rela
     *
     * @mbggenerated Tue Apr 30 21:29:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserPeerRela record, @Param("example") UserPeerRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_peer_rela
     *
     * @mbggenerated Tue Apr 30 21:29:10 CST 2019
     */
    int updateByExample(@Param("record") UserPeerRela record, @Param("example") UserPeerRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_peer_rela
     *
     * @mbggenerated Tue Apr 30 21:29:10 CST 2019
     */
    int updateByPrimaryKeySelective(UserPeerRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_peer_rela
     *
     * @mbggenerated Tue Apr 30 21:29:10 CST 2019
     */
    int updateByPrimaryKey(UserPeerRela record);
}